package com.example.api.model.enumeration;

public enum PrivilegeEnum {

    IMAGE_UPLOAD_PRIVILEGE,
    IMAGE_DOWNLOAD_PRIVILEGE,
    IMAGE_DELETE_PRIVILEGE,
    IMAGE_FULL_ACCESS_PRIVILEGE,
    IMAGE_READ_PRIVILEGE,
    FILTER_READ_PRIVILEGE, FILTER_APPLY_PRIVILEGE

}
