server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gauss
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    consumer:
      group-id: images.wip-consumer-group-2
    producer:
      transaction-id-prefix: images.done-producer-2