server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gray
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    consumer:
      group-id: images.wip-consumer-group-1
    producer:
      transaction-id-prefix: images.done-producer-1