server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    sasl:
      username: admin
      password: password
    topic:
      processing-topic: "images.wip"
      done-topic: "images.done"
      partitions-number: 2
      replication-factor: 3
      isr: 2
    backoff:
      interval: 500
      max-failure: 3

jwt:
  secret:
    access:
      key: B6E5061FADAD40CCAEBDD0F4B3EB3DEE3F4FCE86695FA0076BA9E0A894A53140
      expiration: 1000

file:
  max-size: 10485760
  allowed-format: png, jpeg

minio:
  url: http://localhost:9000
  accessKey: user
  secretKey: password
  bucket: image-storage
  image-size: 10485760