name: api-workflow

on:
  push:
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'

jobs:
  complicated:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: oracle
          cache: maven

      - name: build project
        run: mvn clean compile

      - name: checkstyle
        run: mvn checkstyle:check

      - name: run tests
        run: mvn clean install

      - name: add coverage to PR
        if: ${{ github.event_name == 'pull_request' }}
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/api/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50

      - name: log in to Docker Hub
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: extract metadata for Docker
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        id: meta
        uses: docker/metadata-action@v3.1.0
        with:
          images: shipim/image-project

      - name: build and push Docker image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}